class Config:

    BASE_URL = 'http://127.0.0.1:5000'
    SIDE_DISTANCE = 0.2
    TARGET_ALT = 0.5

    PHEROMONE_INTENSITY = 500
    MOVE_NORTH = (SIDE_DISTANCE, 0, TARGET_ALT, 0)
    MOVE_SOUTH = (-SIDE_DISTANCE, 0, TARGET_ALT, 0)
    MOVE_EAST = (0, SIDE_DISTANCE,TARGET_ALT, 0)
    MOVE_WEST = (0, -SIDE_DISTANCE,TARGET_ALT, 0)
    DEFAULT_COORD = (0, 0, TARGET_ALT, 0)